# This module reads AC-Core outputs / writes observed evidence.
# It must not implement compiler logic.
"""
Local executor: materialize benchmark plans into runnable scripts.

In v1 we do not actually run kernels. `materialize()` writes a small
shell + python script bundle so an operator (or a CI runner) can execute
the plan on a machine with the right hardware.

The point is to make the dry-run mode produce real, inspectable scripts
that show exactly what AC-Harness intends to measure.
"""
from __future__ import annotations

import json
import os
from typing import Any

from ..schemas import ExperimentPlan


_SHELL_HEADER = """#!/usr/bin/env bash
# AC-Harness materialized run script.
# This file was generated; do not edit by hand.
# Generated for ExperimentPlan id={plan_id}, type={plan_type}.
set -euo pipefail
"""

_PY_RUN_TEMPLATE = '''"""
AC-Harness materialized runner stub.

This script is a placeholder. It loads the plan JSON, prints what would
be measured, and writes a faux results file so the import path can be
exercised end-to-end without GPUs. Replace with a real runner that
calls into your kernel/serving harness.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main(plan_path: str, out_path: str) -> None:
    plan = json.loads(Path(plan_path).read_text())
    candidate_ids = plan.get("candidate_ids", [])
    benchmark_type = plan.get("benchmark_type") or plan.get("experiment_type", "unknown")
    print(f"[dry-run] would benchmark {benchmark_type} for {candidate_ids}")
    placeholder = {
        "benchmark_type": benchmark_type,
        "hardware_id": plan.get("hardware_id"),
        "runtime": plan.get("runtime"),
        "results": [
            {"candidate_id": c, "metrics": {}}
            for c in candidate_ids
        ],
        "notes": "Placeholder result generated by AC-Harness dry-run runner.",
    }
    Path(out_path).write_text(json.dumps(placeholder, indent=2))
    print(f"[dry-run] wrote placeholder results to {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: run.py <plan.json> <out.json>")
    main(sys.argv[1], sys.argv[2])
'''


def materialize(
    plan: ExperimentPlan,
    output_dir: str,
    *,
    extra_config: dict[str, Any] | None = None,
) -> list[str]:
    """Write plan.json + run.py + run.sh into output_dir. Returns the list of
    files written (absolute paths).
    """
    os.makedirs(output_dir, exist_ok=True)
    plan_json_path = os.path.join(output_dir, "plan.json")
    run_py_path = os.path.join(output_dir, "run.py")
    run_sh_path = os.path.join(output_dir, "run.sh")

    payload: dict[str, Any] = json.loads(plan.model_dump_json())
    if extra_config:
        payload["config"] = {**payload.get("config", {}), **extra_config}

    with open(plan_json_path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)

    with open(run_py_path, "w") as f:
        f.write(_PY_RUN_TEMPLATE)

    with open(run_sh_path, "w") as f:
        f.write(_SHELL_HEADER.format(plan_id=plan.id, plan_type=plan.experiment_type))
        f.write("python run.py plan.json results.json\n")
    os.chmod(run_sh_path, 0o755)
    os.chmod(run_py_path, 0o755)

    return [plan_json_path, run_py_path, run_sh_path]
